## FIle Parametri scritto con YAML


file:
    input: ./inputData/red_elegansData.data
    dirOut: ./outDummy/Elegans
    
    output: fout_Elegans

# colonne di input e output nel dataframe
    inCol: 4x
    outCol: label 

# nome delle classi di output
    nameClasses: ["linker", "nucleosome"]

parametri_rete:   
    kernel_length: [3, 5]
    filters1: 32
    filters2: 64

training:
    epochs:  [10, 20]
    k_fold: 10
    folds: 2
    
    batch_size: 40
    validation_split: 0.1
    verbose: 0
    
    training_size: -1
    shuffle: False
    


    
    
